# -*- coding: utf-8 -*-
"""Unemployment_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aK33PxJ0ikoK7JWncXq_ddAwpzKB1Opu

# **UNEMPLOYMENT DATA ANALYSIS**

Importing Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

"""Importing Dataset"""

dataset= pd.read_csv('/content/Unemployment_Rate_upto_11_2020.csv')

"""Data Analysis"""

dataset.head()

dataset.describe()

dataset.shape

dataset.corr()

# For checking missing values
dataset.isnull().sum()

"""Visualisation"""

#HeatMap
plt.style.use('seaborn-ticks')
plt.figure(figsize=(12, 10))
sns.heatmap(dataset.corr(), annot=True,cmap='autumn')
plt.show()

sns.pairplot(dataset)

#unemployment rate according to different regions of India
dataset.columns= ["State","Date","Frequency","EUR","EE","ELPR","Region","longitude","latitude"]

plt.figure(figsize=(10, 8))
plt.title("Unemployment Rate")
sns.histplot(x="EUR", hue="Region", data=dataset)
plt.show()